name       : gnome-shell-extension-appindicator
version    : '53'
release    : 1
source     :
    - https://github.com/ubuntu/gnome-shell-extension-appindicator/archive/refs/tags/v53.tar.gz : a1f26e70f651bd05be5e90f0b1f62446861fc191a50452813a960502947f2d52
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : AppIndicator/KStatusNotifierItem/Legacy icons support for GNOME Shell
description: |
    This extension integrates Ubuntu AppIndicators and KStatusNotifierItems (KDE's blessed successor of the systray) into GNOME Shell. Including support for legacy tray icons.
builddeps  :
    - jq
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
replaces   :
    - gnome-shell-extension-topicons-plus
